# Generated by Django 4.2.1 on 2023-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedTasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grape', models.TextField(blank=True, max_length=30, null=True, verbose_name='ブドウ品種')),
                ('country', models.TextField(blank=True, max_length=30, null=True, verbose_name='国')),
                ('coolness', models.CharField(blank=True, choices=[('1.澄んだ', '1.澄んだ'), ('2.深みのある', '2.深みのある'), ('3.やや濁った', '3.やや濁った'), ('4.濁った', '4.濁った')], max_length=30, null=True, verbose_name='清涼感')),
                ('shine', models.CharField(blank=True, choices=[('1.輝きのある', '1.輝きのある'), ('2.艶のある', '2.艶のある'), ('3.モヤがかった', '3.モヤがかった')], max_length=30, null=True, verbose_name='輝き')),
                ('tone', models.CharField(blank=True, choices=[('1.紫がかった', '1.紫がかった'), ('2.オレンジがかった', '2.オレンジがかった'), ('3.黒みを帯びた', '3.黒みを帯びた'), ('4.縁が明るい', '4.縁が明るい'), ('5.ルビー(ラズベリーレッド)', '5.ルビー(ラズベリーレッド)'), ('6.ガーネット(ダークチェリーレッド)', '6.ガーネット(ダークチェリーレッド)'), ('7.トパーズ', '7.トパーズ'), ('8.マホガニー', '8.マホガニー'), ('9.レンガ', '9.レンガ')], max_length=30, null=True, verbose_name='色調')),
                ('shade', models.CharField(blank=True, choices=[('1.無色に近い', '1.無色に近い'), ('2.明るい', '2.明るい'), ('3.やや明るい', '3.やや明るい'), ('4.やや濃い', '4.やや濃い'), ('5.濃い', '5.濃い'), ('6.非常に濃い', '6.非常に濃い')], max_length=30, null=True, verbose_name='濃淡')),
                ('viscosity', models.CharField(blank=True, choices=[('1.さらっとした', '1.さらっとした'), ('2.やや軽い', '2.やや軽い'), ('3.やや強い', '3.やや強い'), ('4.強い', '4.強い')], max_length=30, null=True, verbose_name='粘性')),
                ('freshhness', models.CharField(blank=True, choices=[('1.若々しい', '1.若々しい'), ('2.若い状態を抜けた', '2.若い状態を抜けた'), ('3.やや熟成した', '3.やや熟成した'), ('4.熟成した', '4.熟成した'), ('5.酸化熟成のニュアンス', '5.酸化熟成のニュアンス'), ('6.酸化が進んだ', '6.酸化が進んだ')], max_length=30, null=True, verbose_name='若さ')),
                ('Maturity', models.CharField(blank=True, choices=[('1.軽快な', '1.軽快な'), ('2.成熟度が高い', '2.成熟度が高い'), ('3.濃縮感が強い', '3.濃縮感が強い')], max_length=30, null=True, verbose_name='成熟度')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
    ]
